# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "nft-exchange"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

assets = { directory = "./dist/client" }

# D1 Database Binding
# https://developers.cloudflare.com/d1/
d1_databases = [
  { binding = "DB", database_name = "nft-exchange", database_id = "b8152478-4cad-4769-ba8e-afd055db175f"}
]

build = { command = "" }

# R2 Storage Binding (for image uploads)
# https://developers.cloudflare.com/r2/
[[r2_buckets]]
binding = "R2"
bucket_name = "nft-exchange-images"
preview_bucket_name = "nft-exchange-images"

# Queue for share image generation
# https://developers.cloudflare.com/queues/
[[queues.producers]]
binding = "SHARE_IMAGE_QUEUE"
queue = "share-image-queue"

# Environment Variables
[vars]
CONTRACT_ADDRESS = "0x06fB7424Ba65D587405b9C754Bc40dA9398B72F0"
USDC_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"

# Scheduled Workers (Cron Triggers)
# Run the event indexer every 2 minutes
[triggers]
crons = ["*/2 * * * *"]
