# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "nft-exchange"
main = "src/index.js"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[build]
command = ""

[assets]
directory = "./dist/client"

# D1 Database Binding
# https://developers.cloudflare.com/d1/
[[d1_databases]]
binding = "DB"
database_name = "nft-exchange"
database_id = "b8152478-4cad-4769-ba8e-afd055db175f"

# R2 Storage Binding (for image uploads)
# https://developers.cloudflare.com/r2/
[[r2_buckets]]
binding = "R2"
bucket_name = "nft-exchange-images"

# Environment Variables
[vars]
CONTRACT_ADDRESS = "0x06fB7424Ba65D587405b9C754Bc40dA9398B72F0"
USDC_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
NEYNAR_API_KEY = "YOUR_NEYNAR_API_KEY_HERE" # IMPORTANT: Replace with your actual Neynar API key

# Scheduled Workers (Cron Triggers)
# Run the event indexer every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# D1 Migrations
# https://developers.cloudflare.com/d1/platform/migrations/#local-development
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["D1Database", "D1PreparedStatement", "D1Result"]
# The directory of migrations to apply to the database for this version.
# All .sql files within this directory will be applied in alphabetical order.
migrations_dir = "migrations"
